version: '3'

services:
  web:
    volumes:
      - ./:/home/node/www:Z
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
    ports:
      - "9229:9229"

  mongo:
    ports:
      - "27017:27017"
